### ISSUE TITLE
Date bug with secrets

### ISSUE THREAD

**Issue by NikoTurunen** [joniturunen/blurby#10]
There might be a bug on "date counting/TTL" for the secrets. 

I've run Blurby in container for 6 days.  I tested it right after the deploy and it worked perfectly. But now since blurby's container has run for 6 days, all new secrets get wrong date created and they wont work once linked forward since the TTL time is already gone. 

Its 09/08/2022 15:25 and I just created new secret. When I open the secret and check its "Message will be kept untill" it shows "2022-08-05 13:22:21.199181" which was 4 days ago.

**Comment by joniturunen** [comment]
Thanks for submitting! SQL schema received a function result rather than the function itself. Therefore default timestamp values were generated the same. Fix coming up soon.
